# Let's try Numpy Arrays
In this notebook we will see many different ways in which a notebook can be created

## Exercise 1 numpy import and an array creation
Given the lists: 
`l1 = [0., 1., 2.]`
`l2 = [True, False]`
creates the corresponding numpy arrays and print their types 

In [1]:
import numpy as np
l1 = [0., 1., 2.,]
l2 = [True, False]
a = np.array(l1)
b = np.array(l2)
print(a)
print(b)
# this is how you access to the type of the elements of the array
print(a.dtype) 
print(b.dtype) 
# this print instead that a is a numpy array
type(a)


[0. 1. 2.]
[ True False]
float64
bool


numpy.ndarray

## Exercise 2 creates a multidimensional array

First creates a multidimensional array from the given list of lists
`l1 = [[[0., 1., 2.],[3., 4., 5.]],[[6., 7., 8.],[9., 10., 11.]]]`

Then print the number of **rows** and **columns** of the arrays

In [2]:
l = [
    [
        [0., 1., 2.],
        [3., 4., 5.]]
    ,
     [
         [6., 7., 8.],
         [9., 10., 11.]
     ]
]
a = np.array(l)
print(a)

print(a.shape)

columns = a.shape[-1] # columns are the always last dimension
rows = a.shape[-2] # rows are the second last dimension
print(f"Number of rows {rows}, columns {columns}")

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]
(2, 2, 3)
Number of rows 2, columns 3


## Exercise 3 creates a ndarray with values without using lists
Create:
1) an ndarray 3 x 3 of $1$s 
2) an ndarray 2 x 2 of $0$s
3) an ndarray 1 x 2 of $9$s
4) an ndarray of shape () with value 39
5) an ndarray of shape (2,5) with values randomly distributed between 0 and 1
6) an ndarray with 100 elements between 0 and 5

*note*: always print the ndarray to console to make sure you correctly created

In [3]:
m1 = np.ones((3,3))
print("m1:", m1)

m2 = np.zeros((2, 2))
print("m2:", m2)

m3 = np.full((1, 2), 9)
print("m3:", m3)

m4 = np.full((), 39)
print("m4:", m4)

m5 = np.random.random((2,5))
print("m5:", m5)

# m6 solution 1 np.arange
m6 = np.arange(0, 5, 5/100)
print("m6-arange:", m6)

# m6 solution 2 np.linspace
m6 = np.linspace(0, 5, 100)
print("m6-linspace:", m6)

m1: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
m2: [[0. 0.]
 [0. 0.]]
m3: [[9 9]]
m4: 39
m5: [[0.84739668 0.98109604 0.38188665 0.54634278 0.2912792 ]
 [0.80821805 0.65398582 0.32294714 0.12028004 0.64032157]]
m6-arange: [0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.   1.05 1.1  1.15 1.2  1.25 1.3  1.35
 1.4  1.45 1.5  1.55 1.6  1.65 1.7  1.75 1.8  1.85 1.9  1.95 2.   2.05
 2.1  2.15 2.2  2.25 2.3  2.35 2.4  2.45 2.5  2.55 2.6  2.65 2.7  2.75
 2.8  2.85 2.9  2.95 3.   3.05 3.1  3.15 3.2  3.25 3.3  3.35 3.4  3.45
 3.5  3.55 3.6  3.65 3.7  3.75 3.8  3.85 3.9  3.95 4.   4.05 4.1  4.15
 4.2  4.25 4.3  4.35 4.4  4.45 4.5  4.55 4.6  4.65 4.7  4.75 4.8  4.85
 4.9  4.95]
m6-linspace: [0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
 0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
 0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
 0.90909091 0.95959596 1.01010101 1.06060606 1.11111111 1.1616

In [4]:
type(m4) # It is still a numpy array!

numpy.ndarray

In [7]:
m5_2 = np.random.random((2,5)) # Of course if we call again the np.random.random function we get different values
print("Is m5_2 equal to m5?", np.array_equal(m5, m5_2))

# Below a way to directly inspect the values of the array provided by jupyter notebooks: as last line of a cell
# you call a variable without assigning anything. It would not work in a standard python script.
m5_2 

Is m5_2 equal to m5? False


array([[0.98108014, 0.71498218, 0.19154822, 0.27350623, 0.28060004],
       [0.61517536, 0.38823665, 0.23241987, 0.5288957 , 0.12138251]])