# Let's makes some Numpy Operations
In this notebook, we will make some operations with Numpy arrays. We will use the following functions:
- Universal functions
- Aggregation functions
- Sorting
- Broadcasting


## Exercise 1 Universal Functions
Given an ndarray x = [4, -1, 7, 9, 3, -5] compute the sigmoid function $ y = sigmoid(x)$ which maps numbers $(-\inf +\inf) \rightarrow (0,1)$

$$ sigmoid(x) = \frac{1}{1 + e^{-x}}$$

In [1]:
import numpy as np
np.set_printoptions(precision=3)

x1 = np.array([4, -1, 7, 9, 3, -5])
print(x1)

y_sigm = 1/ (1 + np.exp(-x1))
print(y_sigm)

[ 4 -1  7  9  3 -5]
[0.982 0.269 0.999 1.    0.953 0.007]


## Exercise 2 Aggregation functions
Given an array 
x = [
    [2, 3, -4,],
    [7, 5, 9]
]

Return the mean of the elements along the rows and the minimum element along the columns

In [2]:
x2 = np.array(
    [
        [2, 3, -4,], 
        [7, 5, 9]
    ]
)
print("x", x2)
print(x2.shape)

# mean along the rows --> mean between the columns --> the columns are the dimension to collapse --> axis=-1
print("Mean", x2.mean(axis=-1))

# min along the columns --> mean between the rows --> the rows are the dimension to collapse --> axis=-2
print("Min", x2.min(axis=-2))

x [[ 2  3 -4]
 [ 7  5  9]]
(2, 3)
Mean [0.333 7.   ]
Min [ 2  3 -4]


## Exercise 3 Sorting
Given the same array as in Ex. 1, i.e., x = [4, -1, 7, 9, 3, -5], find the 3 highest values and the positions of the 2 lowest values

In [9]:
x1 = [4, -1, 7, 9, 3, -5]

# sort for getting the values (take the last three to get the highest)
print(np.sort(x1)[:-4:-1])

# argsort for getting their positions (take the first two to get the lowest)
print(np.argsort(x1)[:2])

[9 7 4]
[5 1]


# Exercise 4 Broadcasting
Compute the product between the array x1 = [[0,1,2], [3,4,5]] and the array x2 = [1, 2]
Does it raise an error? How shall x2 be modified to make the operation possible?


In [3]:
x1 = np.array([[0,1,2], [3,4,5]])
x2 = np.array([1, 2])

# print(x1 * x2) # THIS DOES NOT WORK: operands cannot be broadcast together with shapes (2,3) (2) --> (2,3) (1,2) -> (2,3) (2,3) 

# x2 should be reshaped to (2,1) to be broadcasted with x1
x3 = np.array(
    [
        [1], 
        [2]
    ]
)
print("Shape of x3:", x3.shape)
print(x1 * x3)

Shape of x3: (2, 1)
[[ 0  1  2]
 [ 6  8 10]]
