# Let's manipulate some arrays! 
In this notebook we will see different wasy in which we can manipulate an array

## Exercise 1 Array accessing 
Given an ndarray x = [[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]]
Return two arrays:
1) Compute the mean of the elements along the second column 
2) Retrieve the elements with values higher than 2 along the second and third rows 

In [2]:
import numpy as np
x = np.array([[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]])
print(x)

# mean of the elements along the second column
mean_1 = np.mean(x[:, 1]) # mean of the column vector at index 1
mean_2 = np.mean(x, axis=0)[1] # mean of all the columns (along the columns i.e., collapsing the rows -> axis=0)
print("mean second column", mean_1, "or ", mean_2)

# retrieve elements along the 2 and 3 rows if values higher than 2
x2 = x[[1,2]] # select the 2nd and 3rd rows
mask = x2 > 2 # mask to select values higher than 2
print("x2", x2[mask])

[[3. 2. 5.]
 [1. 4. 2.]
 [6. 7. 8.]]
mean second column 4.333333333333333 or  4.333333333333333
x2 [4. 6. 7. 8.]


## Exercise 2 Array accessing to update
Given the previous array x = [[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]]
1) set the values of the first column to 0, if they are greater than 2
2) then try to do the same for the first and third columns together. Does it work? 

In [11]:
x = np.array([[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]])
print(x) 

# first create a mask to select values greater than 2
mask = x[:, 0] > 2
x[:, 0][mask] = 0
print("first update\n", x)

# this would not work: this would set all the values along the first and third columns to 0 
# because the mask is applied array-wise, not to the first column only
# x[mask] = 0 

# This would not work either: x2 is a copy of the selected values, not a view of x
# x2 = x[:, [0,2]][mask]
# x2 = 0
# print("second update\n", x) 

x = np.array([[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]])
mask = x[:,[0,2]] > 2
x[:, [0,2]][mask]= 0
print("second update\n", x) # THIS DOES NOT GET UPDATED! BECAUSE x[:, [0,2]] ALREADY RETURNS A COPY, NOT A VIEW OF X

[[3. 2. 5.]
 [1. 4. 2.]
 [6. 7. 8.]]
first update
 [[0. 2. 5.]
 [1. 4. 2.]
 [0. 7. 8.]]
second update
 [[3. 2. 5.]
 [1. 4. 2.]
 [6. 7. 8.]]


## Exercise 3 Array concatenation and reshaping
Given two arrays x1 = [[3,1], [2,4]] and x2 = [[3, 4], [2,4], [2,5]]

Try to concatenate them vertically and then horizontally.
If something does not work try to reshape the arrays so that you can concatenate (or stack) them.

*Remember*: arrays can be concatenated if and only if all the dimensions match, with the **only exception of the concatenation dimension**.

In [14]:
x1 = np.array([[3,1], [2,4]])
x2 = np.array([[3, 4], [2,4], [2,5]])
print("x1\n", x1)
print("x2\n", x2)

print("x1, x2 vertical concatenation\n", np.concatenate((x1, x2), axis=-2)) # concatenate on the rows dimensions

# print("x1, x2 vstack\n", np.vstack((x1, x2))) # same result as above

# print(np.concatenate((x1,x2), axis=1)) # DOES NOT WORK: dimension along the axis of **not** concatenation must match!
# print(np.hstack((x1,x2))) # same as above

# reshape x2 so that the dimensions of not concatenation (number of rows) match
x3 = x2.reshape((2,3))
print("x3\n", x3) # check out how x3 elements have been placed in the reshaped array

print("x1, x3 horizontal concatenation\n", np.concatenate((x1, x3),axis=1))
# print(np.hstack((x1, x3)) # same as above

x1
 [[3 1]
 [2 4]]
x2
 [[3 4]
 [2 4]
 [2 5]]
x1, x2 vertical concatenation
 [[3 1]
 [2 4]
 [3 4]
 [2 4]
 [2 5]]
x3
 [[3 4 2]
 [4 2 5]]
x1, x3 horizontal concatenation
 [[3 1 3 4 2]
 [2 4 4 2 5]]
